server:
 port: 8005
 
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: Password12
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    
 
eureka:
  instance:
    prefer-ip-address: true
  client:
   fetch-registry: true
   register-with-eureka : true
   service-url:
     defaultZone: http://localhost:8761/eureka